version: "3"
services:
  web:
    build: ./express.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:home/node/code
      - /home/node/code/node_modules
    links:
      - db


  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
#    volumes:
#      - .:/home/node/code
#      - /home/node/code/node_modules
#    links:
#      - db
#    environment:
#      MONGO_CONNECTION_STRING: mongodb://db:27017
