### to use this manual test suite open it IDE like WebStorm or simlia

### GET request
GET http://localhost:3000/user/login/
Content-Type: application/json

{
  "login": "drdre",
  "password": "N.W.A and Ruthless Records"
}

### POST request with a body
POST http://localhost:3000/product/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6Im9saXZpYSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MDM5NDY5NTl9.VxWQxX5Py9MXBQyZwue7V6bgvZz1S3Kh8ZRiQ-9Vr6Q
Content-Type: application/json

{
  "title": "silk",
  "price": 120
}

### GET request
GET http://localhost:3000/user/login/
Content-Type: application/json

{
  "login": "olivia",
  "password": "Surviving Compton"
}

### POST request with a header
POST http://localhost:3000/encart/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6Im9saXZpYSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MDM5NDY5NTl9.VxWQxX5Py9MXBQyZwue7V6bgvZz1S3Kh8ZRiQ-9Vr6Q

[
 42,
  24
]

### GET request
GET http://localhost:3000/user/login/
Content-Type: application/json

{
  "login": "curtis",
  "password": "Move to Aftermath Entertainment"
}

### PATCH request with a header
PATCH http://localhost:3000/purchase/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6ImN1cnRpcyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MDM5NTM1NDZ9.Om19FTuVJs0mDyQRO67QzFVGB02hMvQLp6iVE3mQ9OI
Accept: application/json

### POST request with a body
POST http://localhost:3000/user/signup/
Content-Type: application/json

{
  "login": "olivia5",
  "password": "Surviving Compton",
  "budget": 0
}

